# Generated by Django 4.0.4 on 2022-05-28 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('academic_degree', models.CharField(blank=True, choices=[('baccalaureate', 'بكلوريا'), ('licence', 'ليسانس'), ('master', 'ماستر'), ('doctorate', 'دكتوراه')], max_length=35, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
