# Generated by Django 4.0.4 on 2022-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='aphasia_type',
            field=models.CharField(blank=True, choices=[('healthy', 'غير مصاب'), ('wernicke', 'حسية'), ('broca', 'حركية'), ('mixte', 'مختلطة'), ('conduction', 'توصيلية'), ('conduction', 'نسيانية'), ('global', 'كلية')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('elementry-school', 'إبتدائي'), ('middle-school', 'متوسط'), ('high-shool', 'ثانوي'), ('baccalaureate', 'بكلوريا'), ('licence', 'ليسانس'), ('master', 'ماستر'), ('doctorate', 'دكتوراه')], max_length=35, null=True),
        ),
    ]
